---
- name: Ensure packages database is up to date
  become: yes
  apt: update_cache=yes

- name: Install Apache
  become: yes
  apt: pkg=apache2 state=latest

- name: Install Apache Modules
  apache2_module: state=present name={{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

- name: Get installed version of Apache.
  shell: apache2 -v
  changed_when: false
  register: apache_version

- name: Change default apache2.4 site
  become: yes
  template: src=vhost24.conf.tpl dest=/etc/apache2/sites-available/{{ item.config_name }}
  notify: restart apache
  when: apache_version.stdout.find('Apache/2.4.') != -1
  with_items:
    - "{{ apache.hosts }}"

- name: Change default apache2.2 site
  become: yes
  template: src=vhost22.conf.tpl dest=/etc/apache2/sites-available/{{ item.config_name }}
  notify: restart apache
  when: apache_version.stdout.find('Apache/2.2.') != -1
  with_items:
    - "{{ apache.hosts }}"
